### ISSUE TITLE
Duplicated Terms

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#13]
The 3 terms: 
- behavior (36)
- Mobility (54)
- Transmission settings (61)
are deprecated and duplicated of other terms: behavior (79), mobility (73), and transmission settings (80). 

Could we remove the  behavior (36), Mobility (54) and Transmission settings (61)?

**Comment by hoganwr** [comment]
Some notes:

73 and 80 are also deprecated, having been replaced by Apollo-SV terms.

All deprecated classes are appropriately pointed using "term replaced by"
to their replacements.

Similar to another issue, we need to decide whether we care about not
deleting IRIs.  I'm not sure what the problem is with leaving the
deprecated classes and their IRIs in place.

Merits further discussion.

**Comment by LucieContamin** [comment]
Thanks for the reply and for the clarification. 
I am ok with deprecating the terms (instead of removing, I agree it's better to keep it as deprecated).

**Comment by harryhoch** [comment]
is there anything left here to discuss?

**Comment by hoganwr** [comment]
Decision is to keep old terms/IRIs that are no longer used as deprecated
