### ISSUE TITLE
Medical terms

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#32]
The data catalog entry form contains the terms:

Medical (subclass of Topic): 
    - Clinical Trial (subclass of Medical)

I think it was link to the issue #3. Could we add them in the ontology?

Should we also add 
   - Immonogenicity (child of Medical)?

**Comment by LucieContamin** [comment]
THanks for the update,
I found the two terms: "Immunogen" and "Clinical Trial". However they are subClasses of Topic. Would it be possible to create a new "Medical" term as a SubClass of Topic and transfer "Immunogen" and "Clinical Trial" as SubClass of Medical, please?

To have something like:
Topic -- Medical (Subclass of Topic) -- Immunogen (Subclass of Medical)
Topic -- Medical (Subclass of Topic) -- Clinical Trial (Subclass of Medical)

**Comment by hoganwr** [comment]
Do you have a definition of "Medical"?  What does the adjective modify?  Data set?  Does it mean "medical data set"?

**Comment by LucieContamin** [comment]
I apologize I don't have a clear definition for Medical. I can refer to the issue #3 for more information. If I understand correctly, in this issue the term was link to the definition "Data relating to health care".

**Comment by harryhoch** [comment]
What purpose would the term "medical" serve? Almost all of the ontology relates to health care in some sense. Is there a use case for tying "immunogen" and "clinical trial" together?

**Comment by LucieContamin** [comment]
Currently only the term clinical trial is used in the metadata entry form in the MIDAS DB and it's a child of "medical" as it was in a previous version of the ontology I think.

And following the discussion on the issue #3 , the two terms are often but not always related. I also have an example here: https://accessclinicaldata.niaid.nih.gov/ that might link both if I understand correctly. 

Medical might not be the best term to regroup clinical trial, immunogen and other associated term but I don't have other suggestions currently.

**Comment by harryhoch** [comment]
ok. the fact that we don't have the term medical in a previous version suggest that we might not need it.  Can you describe a use case - a scenario where it might be need?


I couldn't get that link to work....

**Comment by LucieContamin** [comment]
Sorry I was not clear, we had the term medical in a previous version 
```
 <!-- http://midasnetwork.us/datasets#MIDAS_DATA000089 -->

    <owl:Class rdf:about="http://midasnetwork.us/datasets#MIDAS_DATA000089">
        <rdfs:subClassOf rdf:resource="http://midasnetwork.us/datasets#MIDAS_DATA000002"/>
        <rdfs:comment>Data relating to health care</rdfs:comment>
        <rdfs:label xml:lang="en">Medical</rdfs:label>
    </owl:Class>
  ```
It was added on a suggestion from Alice, so might be good to discuss with her again about it. 

The example I join is about Accessing NIAID Clinical Trials Data with data like: "Dataset for IMPACC - A Prospective Cohort Study to Assess Longitudinal Immune Responses in Hospitalized Patients with COVID-19 "

**Comment by harryhoch** [comment]
ok. @aarcury-quandt , what do you think? Do we need the term "medical"? If so, how can we define it?

**Comment by aarcury-quandt** [comment]
I think "medical" was based on anticipating having more types of medical/observational data in the catalog and needing a term for the parent.  
- If the still anticipate having many types of medical/observational data, I think it's useful for the sake of data entry/organization to group terms into a parent and to plan that parent now.  I don't feel strongly about the term "medical".
- If not, then I think clinical trial can be a top level item.

As for the definition for "medical" or whatever other term we use, I guess the question is what makes these datasets (or the studies from which we derived them) different? 

- Data were collected as research or through survey (as opposed to case reports)
- Data were collected at an individual level and reported at an individual level
- The most succinct way I can think to say this because "biological specimens" doesn't quite fit: researcher pokes study participant (clinical trial, seroprevalence) or researcher watches something else poke study participant (biting rates).  This is different from what we see in "Behavior" where bullet 2 may be met, but the interaction is researcher talks to study participant.

Now, we have 2 catalog items labeled with "clinical trial".  One is the NIH database, where it looks like you have individual observations reported.  The other is the IBM thing. I can't get it to open, and I don't think it fits the above definition.   I know of a [old] COVID seroprevalence dataset published with a pre-print, but I don't know if it's catalogued.  So we have potentially 2 datasets that fit these criteria. Maybe more if we go back and look at all the seroprevalence studies that were started in 2020.

**Comment by harryhoch** [comment]
thanks, @aarcury-quandt .   I think the data collected as research are often clinical trials.   Are you talking instead about data collected during clinical care? We can call it "clinical data", but I still think it's very distinct from "immunogen" and "clinical trials". 

 I guess I would also say that seroprelvalence data should have a distinct tag of its own.

**Comment by harryhoch** [comment]
Ok, follow-up.  I think it makes sense to add imunnogen and clinical trials.   @aarcury-quandt , what are the other use cases that you're thinking of?

**Comment by hoganwr** [comment]
They are already there under topic.  If there's nothing else to do with
them then we can close this issue.

**Comment by aarcury-quandt** [comment]
@harryhoch I don't understand the question. Are you asking what sorts of studies from above criteria that I think we'd have data from?  Because I don't know how useful that would be.

**Comment by harryhoch** [comment]
yes - what would be the use cases for the other types of "medical data" - we need specific examples to determine how to model it?

**Comment by aarcury-quandt** [comment]
Off the top of my head: 

- challenge trials (sometimes clinical trials, sometimes not)
- human-vector experiments (to get things like biting rates)
- we already have seroprevalence?
- other types of prevalence like skin punches or skin scrapes
- cytokine studies
- studies about T cell responses (I don't think these fit under immunogenicity) or other studies about what is driving immunity

**Comment by harryhoch** [comment]
Suggest we leave this until specific use cases require action
