### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#34]
The different terms can be written in different "style", for example:
- Case counts (first letter upper case)
- Diagnostic Tests (first letter of each word in upper case)
- infection case list (lower case)
- sequence_collection (lower case and "special character")

Should we choose one "style" to avoid confusion?

**Comment by hoganwr** [comment]
The issue is that we do not use upper case in Apollo-SV, whereas the MIDAS
OWL file was created using some upper case characters.

If we want to have a single style, we could either (1) adapt MIDAS OWL file
terms to the Apollo-SV convention (which is constrained by OBO Foundry
conventions, so not malleable) or (2) create a new annotation property like
"MIDAS preferred name" and enforce consistent style on that property.

**Comment by harryhoch** [comment]
I'm ok with simply revising labels to fit the Apollo-SV approach
