### ISSUE TITLE
Import vaccination class to be parent of other vaccination-related classes

### ISSUE THREAD

**Issue by hoganwr** [midas-network/midas-data#56]
Including vaccination with nirsevimab

**Comment by hoganwr** [comment]
Note recent changes for review:
1. incident and cumulative counts under "case counts" class
2. intent to be vaccinated
3. vaccination with nirsevimab
4. infectious agent seroprevalence

**Comment by LucieContamin** [comment]
Thank you for the update, I have some questions: 

## Incident and cumulative counts

The incident and cumulative case, death, hospitalization, and vaccination have been added. And we have some topics that include these topics. For example: "mortality data" is used for all rate, percent, counts (cumulative or not) of death data. The new terms are more detailed and do not include percent or rate as I understand. 

#### Definition

I noticed that all the new term are link to specific epidemic and the case counts ontology contains "A count of cases from the beginning of the epidemic until recently". However the case/death/hospitalization/etc. counts we have are not always related to a specific epidemic and we don't always have the start and/or the most recent data.

#### Hierarchy

However, these new terms are all subclass of "case counts" in the ontology, which is confusing for me. 
As of now in the ontology we have:
    - mortality data
    - control strategy census
        -  vaccination administration census
    - case counts
        -  hospital stay dataset

So, should we have:
- the new cumulative/incident case subclass of case counts ?
- the new cumulative/incident death subclass of mortality data ?
- the new cumulative/incident vaccination subclass of hospital stay ?
- the new cumulative/incident hospitalization subclass of hospital stay dataset ?


## Intent to be vaccinated

Should they be subclass of "behavior"?
Also, I am not sure I understand the "intent to vaccinate" topic, will it include data about vaccination campaign for example?
Or does it include also parent wanting to have their child vaccinated?

## Nirsevimab

The nirsevimab topic is added as "vaccination with nirsevimab", is it correct? Sorry I got a little confused on if it is called a vaccination or not.
Also, should it be subclass of "control strategy census"?

## Seroprevanlence

 I see the new seroprevalence topic in the ontology and was wondering if it makes sense to group it with the topic "immunogen"?

**Comment by hoganwr** [comment]
To address the comments:

1. Yes, we discussed counts as being the key classes required and thus created only count classes.  If additional classes are needed for rates, we could look at those as well.  Please let us know specifically what rates are needed.
2. Yes, we also discussed things in the context of epidemic data. I did happen to create more general classes that are not specifically linked to epidemics.  I created an issue here: https://github.com/midas-network/midas-data/issues/57
3. With respect to start and end date, I was careful to craft the definitions to account for the fact that we don't often know the exact start/end dates.  However, if there's a better way to define 'cumulative' such as "assumed epidemic start date" or "estimated epidemic start date", I'd be happy to revise the definitions accordingly.
4. I created an issue to reparent various classes per above: https://github.com/midas-network/midas-data/issues/58
5. Intent to vaccinate was intended as things like vaccine campaign.  The case of the parent intending to vaccinate their child is not covered by the current definition. We would need to create a new class for this.  If you need this class, let us know and I'll add an issue.
6. added nirsevimab to reparenting issue https://github.com/midas-network/midas-data/issues/58
7. If you have a preferred grouping that covers both immunogen and seroprevalence, let us know.  Otherwise, we'll come up with a proposal and post an issue.

**Comment by LucieContamin** [comment]
Thank you very much for the answer, here are my comments, please @alc172 feel free to review:

1. I will double check, but I don't think we need rates as of now, thank you! I will open an issue if so. 

2. I am not sure I totally understand, does that mean that more class that are not epidemic related are going to be added? In this case are we going to keep the epidemic one?  

3. It's a difficult one, I think we have some data where we have only a portion of a time series and/or does not start at 0 ( and not always related to an epidemic or pandemic event). That's why I am worrying about the "entire temporal interval occupied by the epidemic" and "from the beginning of the epidemic until recently." parts of the cumulative class definition. Will it make sense to be even broader. I will check our data in more details, and try to open quickly an issue representing the issue and range of "cumulative" variables with have to give more context. 

4. Thanks, I add a small comment on the issue

5. I have a Nirsevimab dataset that is about "intent for baby’s receipt of nirsevimab reported by females aged 18-49 years with infants under the age of 8 months, females aged 18-49 years who are currently pregnant, and females aged 18-49 years who are currently trying to get pregnant.". In this case, I think we will need the parent intending to vaccinate their child. Should we make it even broader? (not only parent/child but someone intent to vaccinate some else to avoid future issue?)

6. Thanks

7. I don't have a very good suggestion, sorry.

**Comment by hoganwr** [comment]
1. Ok sounds good
2. Yes. It is up to you whether to keep the ones specifiic to epidemics.
3. The interval exists, even if we don't know its exact boundaries.  The
counts are about that interval.  Also the start of the interval is nearly
always human conventions and are fiat boundaries rather than anything in
nature.
4. Sounds great!
5. Ok, will work on a class that captures a parent intending to vaccinate
their child.  An oversight on my part.
6. Now that you suggest moving seroprevalence under case count data,
perhaps it's no longer an issue?

**Comment by LucieContamin** [comment]
Thank you for the answer,
2. I don't think we need to keep the epidemics specific classes
3. this point is related to the issue #59 
5. thank you!
7. Sorry about the confusion about serology. I will answer in the issue #58
