### ISSUE TITLE
Reparenting mortality data and tests topic

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#63]
Following this comment here: https://github.com/midas-network/midas-data/issues/58#issuecomment-2015865184

I thought we were going to re-order some of the topics and especially to obtain:

- case counts (midas 38)
    - mortality data (apollo 542) [subclass of midas 38]
        - excess mortality dataset (apollo 608)  [subclass of apollo 542]
        - cumulative death count (apollo 646) [subclass of apollo 542]
        -  incident death count (apollo 647) ([subclass of apollo 542]
    - dignostic tests (midas 34) [subclass of midas 38]

I saw that the mortality topic was moved in commit [37e2dcc](https://github.com/midas-network/midas-data/commit/37e2dcc9e7cfd9e72163975f20e7e1b00ae8c604) by @harryhoch , but the change was overwrite in a later change.

**Comment by harryhoch** [comment]
@hoganwr, is it possible that I edited the wrong file?  Same with #64?

**Comment by hoganwr** [comment]
Yes it looks like you edited midas-data.owl instead of midas-data-edit.owl. The process is to make the changes in midas-data-edit.owl and then the workflow creates a new midas-data.owl and a new release. I will re-apply these changes in my local clone of the repo and commit them, which will make a new release.
